3-module 3-task
js-tasks-ru/nodejs-20210907_maksim-lobarev pull request #3
Opened 2021-09-17 13:14 UTC by simaks147

Почему-то не проходит тест на вложенные файлы, хотя при запросах вроде все работает как надо, т.е. отдается ошибка 404

2021-09-17 13:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-21 12:19 UTC, simaks147 commented
В третей задаче по стримам нашел ошибку, все тесты по ней теперь проходят

2021-09-21 12:21 UTC, simaks147 commented
В четвертой задаче не проходит один тест, какая-то странная ошибка, не получается исправить
![2021-09-21_15-15-05](https://user-images.githubusercontent.com/12429002/134169419-bec89000-5a49-41ff-958c-f1a7f825e586.png)

2021-09-21 12:23 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-09-21 18:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-21 18:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-09-23 09:59 UTC, tadjik1 requested changes
Заметил пару неточностей

2021-09-23 09:59 UTC, tadjik1 commented on 03-streams/03-file-server-get/server.js
> +    res.end('No such file');
Return нужен в этом условии

2021-09-23 09:59 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +    res.end('No such file');
Здесь нужен return

2021-09-23 09:59 UTC, tadjik1 commented on 03-streams/05-file-server-delete/server.js
> +    res.end('No such file');
Return

2021-09-23 14:39 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-09-23 15:28 UTC, simaks147 commented
Все ретерны добавил, как вы сказали. А вот ошибку никак не получается найти, уже урок пересматривал и решение преподавателя в задачнике смотрел, безуспешно. Все та же ошибка при тестах, что на скрине выше указывал. Помогите пожалуйста!

2021-09-24 09:41 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +      const limitSizeStream = new LimitSizeStream({limit: 10000});
@simaks147  по условиям задачи лимит должен быть 1МБ - т.е. 1000000, а у вас 10000. возможно в этом проблема?

2021-09-24 09:46 UTC, tadjik1 commented
@simaks147 похоже что эта ошибка возникает из-за проблем, связанных с операционной системой. в целом весь код написал верно, и эта ошибка релеватна только для тестов на ОС windows, т.е. в реальной жизни она не будет происходить.

2021-09-24 09:46 UTC, tadjik1 commented on 03-streams/04-file-server-post/server.js
> +      const limitSizeStream = new LimitSizeStream({limit: 10000});
еще один 0 нужен) по условиям задачи лимит - 1мб, т.е. 1000000

2021-09-24 09:47 UTC, tadjik1 approved these changes
хорошее решение 👍 
на линуксе и маке все тесты проходят, все выполнено корректно!

2021-09-24 09:47 UTC, merged